name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title for Jira ticket
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            if (context.payload.pull_request) {
              const jiraPattern = /^[A-Z]+-\d+/;
              if (!jiraPattern.test(context.payload.pull_request.title)) {
                core.setFailed("The PR title must include a Jira ticket in the format: DEV-1234.", {"title": "Invalid PR Title"});
              }
            } else {
              core.setFailed("This action should only run on select pull request events.", {"title": "Invalid Event Context"});");
            }
